### ISSUE TITLE
Re-arrange to follow this layout.

### ISSUE THREAD

**Issue by jonataneriksson** [jonataneriksson/centerfordigitalhealth.upenn.edu#24]
[Task](https://app.trackduck.com/project/59fb51a380f884d349f3a152/issue/59fc908780f884d349f3ad36?utm_source=integration&utm_medium=app_github&utm_content=task) with ***Low*** priority was created by ***Jonatan Eriksson***:

>Re-arrange to follow this layout.

[![Issue screenshot](https://app.trackduck.com/file/crop/59fb51a380f884d349f3a152-1509724295787-1282-711.jpg?utm_source=integration&utm_medium=app_github&utm_content=preview)](https://app.trackduck.com/preview/awsi/59fb51a380f884d349f3a152-1509724295787-1282-711.jpg?utm_source=integration&utm_medium=app_github&utm_content=preview)

Environment: ***Safari 11*** on ***Mac OS*** with ***1363x1347*** screen size.

Attachments:
[Screen Shot 2017-11-03 at 11.50.55 AM.png](https://app.trackduck.com/file/user-file/59fb51a380f884d349f3a152-1509724286352-Screen-Shot-2017-11-03-at-11.50.55-AM.png?utm_source=integration&utm_medium=app_github&utm_content=attachment)

Check it in your [website](http://centerfordigitalhealth.upenn.edu/participate?tdtask=59fc908780f884d349f3ad36) or get [more details...](https://app.trackduck.com/project/59fb51a380f884d349f3a152/issue/59fc908780f884d349f3ad36?utm_source=integration&utm_medium=app_github&utm_content=task)

**Comment by jonataneriksson** [comment]
![59fb51a380f884d349f3a152-1509724286352-screen-shot-2017-11-03-at-11 50 55-am](https://user-images.githubusercontent.com/2415686/33892224-3c65e49e-df26-11e7-925d-62042ff4c015.png)

**Comment by phrequency** [comment]
I thought we removed past events from an earlier email thread.

**Comment by jonataneriksson** [comment]
OK! I might have not been included in that email. 

How about the width of the column? Could we go to 2/3 instead of full width?
